### ISSUE TITLE
@DubboConsumer 和 @MockBean 不兼容

### ISSUE THREAD

**Issue by zimmem** [alibaba/dubbo-spring-boot-starter#21]
不能通过 @org.springframework.boot.test.mock.mockito.MockBean 来 mock @DubboConsumer 标注的属性。

**Comment by xionghuiCoder** [comment]
确实没有处理兼容过@MockBean，后续我了解下这块，清知晓

**Comment by xionghuiCoder** [comment]
最新发布版@DubboConsumer注解调整为了@Reference，请知悉
