### ISSUE TITLE
怎么配置 <dubbo:monitor protocol="registry"/>

### ISSUE THREAD

**Issue by nice2mu** [alibaba/dubbo-spring-boot-starter#24]
怎么配置 <dubbo:monitor protocol="registry"/>

**Comment by xionghuiCoder** [comment]
hi，目前还未支持dubbo监控中心配置

**Comment by xionghuiCoder** [comment]
hi，version 1.0.1和1.0.2已经支持了，可配置:
`spring.dubbo.monitor=address`
以支持MonitorConfig。

**Comment by xionghuiCoder** [comment]
Duplicate of #63
