### ISSUE TITLE
maven pom dependency issue

### ISSUE THREAD

**Issue by avatar21** [alibaba/dubbo-spring-boot-starter#33]
I search all over places for official documentation, tutorials, found following solutions, all not working ... not found in any public maven repository, improve your code & documentation quality please!!!

Don't publish until you have personally tested it working, it's a very basic coding discipline.

```
<dependency>
  <groupId>com.alibaba</groupId>
  <artifactId>spring-boot-starter-dubbo</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>

```
```
<dependency>
  <groupId>io.dubbo</groupId>
  <artifactId>spring-boot-starter-dubbo</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
```

**Comment by xionghuiCoder** [comment]
hi,目前还没有发布release计划,使用时需要clone下来并上传私服；谢谢

**Comment by cooppor** [comment]
@xionghuiCoder 为啥呀，大兄弟，发布上来多好啊

**Comment by xionghuiCoder** [comment]
已经发布中央仓库，请知晓
