### ISSUE TITLE
请问什么有没有打算支持标准 SpringBoot 配置的写法@Configuration

### ISSUE THREAD

**Issue by avatar21** [alibaba/dubbo-spring-boot-starter#34]
这可能不是什么BUG，是功能要求吧。
请问有没有什么打算，支持 标准 SpringBoot 配置的写法，而不是xml配置。
@Configuration 这种...

**Comment by xionghuiCoder** [comment]
hi，目前是支持yaml和properties配置的，你说的xml配置是指dubbo的配置么？
