### ISSUE TITLE
命名规范

### ISSUE THREAD

**Issue by nickevin** [alibaba/dubbo-spring-boot-starter#40]
[官方文档](https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#boot-features-custom-starter-naming)对第三方 Starter 的建议：Do not start your module names with spring-boot, even if you are using a different Maven groupId. **We may offer an official support for the thing you’re auto-configuring in the future.**

可以参考 Mybtais 的 [POM](http://www.mybatis.org/spring-boot-starter/mybatis-spring-boot-autoconfigure/)：

```
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>2.0.0-SNAPSHOT</version>
</dependency>
```

详见：https://docs.spring.io/spring-boot/docs/1.5.9.RELEASE/reference/htmlsingle/#boot-features-custom-starter-naming

**Comment by xionghuiCoder** [comment]
多谢建议，后续考虑调整过来
