### ISSUE TITLE
您好,依赖包不能下载

### ISSUE THREAD

**Issue by charpty** [alibaba/dubbo-spring-boot-starter#42]
```
<dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>spring-boot-starter-dubbo</artifactId>
        <version>1.0.0-SNAPSHOT</version>
</dependency>
```
按照首页的配置引用之后,并不能加载这个依赖,查了中央仓库也没有,是还没上传吗?

**Comment by charpty** [comment]
@xionghuiCoder 麻烦帮忙看下~

**Comment by xionghuiCoder** [comment]
目前已经发布中央仓库，请知晓：
<dependency>
        <groupId>com.alibaba.spring.boot</groupId>
        <artifactId>dubbo-spring-boot-starter</artifactId>
        <version>1.0.0</version>
    </dependency>

**Comment by charpty** [comment]
赞!
