### ISSUE TITLE
如何实现多种协议配置

### ISSUE THREAD

**Issue by wfd0807** [alibaba/dubbo-spring-boot-starter#43]
如何实现多种协议配置，如同时支持dubbo和rest协议？

**Comment by xionghuiCoder** [comment]
dubbo即提供rpc服务，同时提供restful服务？

**Comment by wfd0807** [comment]
@xionghuiCoder 是的，Java消费者使用dubbo协议，非java消费者使用restful的方式，应该怎么配置？

**Comment by Benjar** [comment]
现在的版本是不是还不支持多协议配置？

**Comment by hanwangkun** [comment]
看源码，目前还没支持，同时在一个项目里面发布dubbo协议和hessian协议

**Comment by xionghuiCoder** [comment]
@hanwangkun hi，已经给你发送Add Collaborators请求了；有时间请帮支持下，thx.

**Comment by hanwangkun** [comment]
@xionghuiCoder 好的

**Comment by rongmin** [comment]
期待

**Comment by xionghuiCoder** [comment]
#65

**Comment by sourcecafe** [comment]
现在支持多协议配置了吗？
