### ISSUE TITLE
提供的服务会被注册两次

### ISSUE THREAD

**Issue by liaochong** [alibaba/dubbo-spring-boot-starter#51]
当服务提供和服务消费在同一个包时，提供的服务会被注册两次

**Comment by xionghuiCoder** [comment]
hi，provider和consumer是否在同一个bean内？

**Comment by liaochong** [comment]
不直接存在，provider中引用了一个普通的spring service对象，然后这个service对象中存在一个使用了@Reference引用的consumer

**Comment by xionghuiCoder** [comment]
hi，按照demo配置了下，目前没有重现；问下在demo中是哪个服务会被注册两次？如何发现注册两次的？
另外spring用的哪个版本，有没有配置多例(prototype)模式。
