### ISSUE TITLE
建议添加@Reference version版本自定义实现

### ISSUE THREAD

**Issue by hsiangbinhua** [alibaba/dubbo-spring-boot-starter#52]
在springboot 中一般都是通过profile来区分配置文件，纯注解dubbo的@Reference 来添加版本时，会造成开发、测试、生产环境的版本不一致的困扰！！！
  另外，发现当前版本的spring.dubbo.registry=zookeeper://**.**.**.**:2181 只能配置一个地址，建议添加轮询实现，提供消费服务的可用性！！！

**Comment by xionghuiCoder** [comment]
ok，很好的建议。你愿意帮忙来完善该需求么？

**Comment by xionghuiCoder** [comment]
Duplicate of #50
