### ISSUE TITLE
启动检查关闭dubbo.registry.check，参数怎么设置呢？

### ISSUE THREAD

**Issue by ejshi** [alibaba/dubbo-spring-boot-starter#54]

**Comment by xionghuiCoder** [comment]
consumer端的@Reference设置check为false

**Comment by ejshi** [comment]
dubbo-spring-boot-starter不提供check的全局配置，是吗？

**Comment by xionghuiCoder** [comment]
是的，没有全局配置的；因为需要同时支持provider和consumer，所有全局配置都是provider和consumer共有的一些配置，比如registry等。

**Comment by LiMingCH** [comment]
应该区分的

**Comment by HeroGoSup** [comment]
可以增加dubbo.properties --> dubbo.reference.check=false

**Comment by xionghuiCoder** [comment]
@HeroGoSup 很棒的建议；不过有个问题需要考虑下：什么时候取全局配置（dubbo.reference.check），什么时候取@Reference的check配置？

**Comment by HeroGoSup** [comment]
@xionghuiCoder 优先@reference

**Comment by xionghuiCoder** [comment]
@HeroGoSup 考虑下这两种场景：

- @reference(check=true)和dubbo.reference.check配置为false

- @reference和dubbo.reference.check配置为false

理论上第一种情况应该是check为true，第二种check为false；但是由于@reference的默认值为true，貌似不能区分check是默认值true还是手动设置的true。

**Comment by HeroGoSup** [comment]
@xionghuiCoder  检验第二种dubbo.reference.check配置为false是否生效不就可以了吗

**Comment by xionghuiCoder** [comment]
@HeroGoSup 按上面的逻辑，第一种的check结果为true，第二种的check结果为false；问题在于不能区分@reference(check=true)和@reference。不能实现
