### ISSUE TITLE
与spring-boot-devtools的问题

### ISSUE THREAD

**Issue by crazyatnet** [alibaba/dubbo-spring-boot-starter#59]
dubbo-spring-boot-starter版本1.0.0-SNAPSHOT
spring-boot版本1.5.9.RELEASE
java version "1.8.0_151"
使用spring-boot-devtools启动，扩展点（Filter）加载注入spring bean的时候com.alibaba.dubbo.config.spring.extension.SpringExtensionFactory#getExtension中
`if (type.isInstance(bean)) {`永远为false，所以无法注入bean，不使用spring-boot-devtools就能正常注入

**Comment by xionghuiCoder** [comment]
hi，spring-boot-devtools会使用RestartClassLoader，和bean的classloader可能不同，所以
`if (type.isInstance(bean)){...}`
会返回false，可以尝试配置下spring-devtools.properties，设置classloader一致。

建议下参考该博客：[ spring-boot-devtools 不同ClassLoader引起的问题](http://blog.csdn.net/xichenguan/article/details/73741835)
