### ISSUE TITLE
发布服务的文档写得有误

### ISSUE THREAD

**Issue by hanwangkun** [alibaba/dubbo-spring-boot-starter#61]
发布服务时，在实现类上只使用了@Service这个注解，但实际上它是不能发布成功的，通过查看源代码发现，它必须先是被注入进spring容器里面的一个bean才行，所以还要再加@Repository才能发布服务成功！  所以，请修改下文档，以免初次使用者掉进坑里

**Comment by dlhf** [comment]
对啊,我的天,刚刚就遇到这个问题了,很尴尬,哇,我没过来看 issue
