### ISSUE TITLE
@Configuration 的类无法注入 @Reference

### ISSUE THREAD

**Issue by wcp1231** [alibaba/dubbo-spring-boot-starter#62]
看了一下逻辑，应该是所有 `@Configuration` 都会在运行时被换成 CGLib 生成的子类，所以代码里

https://github.com/alibaba/dubbo-spring-boot-starter/blob/master/src/main/java/com/alibaba/dubbo/spring/boot/DubboConsumerAutoConfiguration.java#L77

是拿不到添加了 `@Reference` 注解的字段的，所以也就不能注入了。

**Comment by xionghuiCoder** [comment]
hi, consumer使用@Configuration注解bean时，bean同时实现SpringProxy接口即可work.

ps: 如果provider使用@Configuration注解时需要在bean的@Service注解加上interfaceClass配置即可，例如: @Service(interfaceClass = XXX.class)

**Comment by wcp1231** [comment]
好的，thx
