### ISSUE TITLE
Remove spring web dependency

### ISSUE THREAD

**Issue by adriancole** [alibaba/dubbo-spring-boot-starter#66]
If you run where the web container is disabled, like "--spring.main.web-environment=false", the process will exit. It seems like we should have instructions for applications who only communicate via dubbo, not running the web container, even if usually they will

**Comment by xionghuiCoder** [comment]
Nice advice, we will support it in dubbo-spring-boot-starter.

**Comment by adriancole** [comment]
Thanks. I will update this once released https://github.com/openzipkin/sleuth-webmvc-example/compare/add-dubbo-tracing
