### ISSUE TITLE
是不是不支持spring boot 2.0额。

### ISSUE THREAD

**Issue by pengliaoye** [alibaba/dubbo-spring-boot-starter#67]
dubbo报Caused by: java.lang.ClassNotFoundException: org.springframework.boot.actuate.endpoint.AbstractEndpoint

**Comment by xionghuiCoder** [comment]
#64 hi, 请试下version 1.0.1，该version去掉了Endpoint。

**Comment by xionghuiCoder** [comment]
#64

**Comment by dlhf** [comment]
这个 dubbo springboot starter 和 dubbo 下的 starter 有什么不一样

**Comment by xionghuiCoder** [comment]
@dlhf #47
