### ISSUE TITLE
dubbo@Service 和spring的@Transactional一起使用， 无法发布服务

### ISSUE THREAD

**Issue by wangzhen-cn** [alibaba/dubbo-spring-boot-starter#9]
dubbo@Service spring的@Transactional一起使用， 无法发布服务，

**Comment by xionghuiCoder** [comment]
hi,能贴下代码和配置么?

**Comment by ef100** [comment]
dubbo用2.5.4，或者用配置文件配置dubbo服务

**Comment by xionghuiCoder** [comment]
提示啥错误？另外@Transactional应该在DAO层，建议和dubbo@Service分开，这样方便代码维护

**Comment by NeverMore93** [comment]
请问为什么https://mvnrepository.com/artifact/com.alibaba里没有这个项目

**Comment by xionghuiCoder** [comment]
hi，目前未发布release版本，请知晓

**Comment by avatar21** [comment]
@wangzhen-cn 　我看见某处有人报过这个BUG，好像解决方案是在Service注释里，必须声明 interface属性。你试试

```
@Service(interfaceClass = IHelloService.class)
public class HelloServiceImpl implements IHelloService {
  //...
}
```

**Comment by xionghuiCoder** [comment]
@NeverMore93 目前已经发布中央仓库，请知悉

**Comment by xionghuiCoder** [comment]
@wangzhen-cn @Service 注解需要和Spring的四大初始化bean注解配合使用：
* @Component
* @Controller
* @Service
* @Repository
使用事务是可以加上@Repository就可以发布服务了。
